- hosts: ldap
  tasks:

    - name: install ldap
      become: yes
      yum:
        state: present
        name:
          - openldap
          - compat-openldap
          - openldap-clients
          - openldap-servers
          - openldap-servers-sql
          - openldap-devel

    - name: start & enable ldap
      become: yes
      service:
        name: slapd
        state: started
        enabled: yes

